version: '3.7'

services:
  database:
    image: 'postgres:latest'
    container_name: wish-list-database
    restart: always
    ports:
      - '5431:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
